name: Smart AI Contribution Bot

on:
  schedule:
    # Target: ~60 scheduled runs per day for 50+ successful contributions
    # Every 25-30 minutes with random minute offsets for natural pattern
    - cron: '7 0 * * *'    # 12:07 AM
    - cron: '23 0 * * *'   # 12:23 AM
    - cron: '41 1 * * *'   # 1:41 AM
    - cron: '15 2 * * *'   # 2:15 AM
    - cron: '33 2 * * *'   # 2:33 AM
    - cron: '52 3 * * *'   # 3:52 AM
    - cron: '18 4 * * *'   # 4:18 AM
    - cron: '37 4 * * *'   # 4:37 AM
    - cron: '9 5 * * *'    # 5:09 AM
    - cron: '28 5 * * *'   # 5:28 AM
    - cron: '46 6 * * *'   # 6:46 AM
    - cron: '11 7 * * *'   # 7:11 AM
    - cron: '29 7 * * *'   # 7:29 AM
    - cron: '48 8 * * *'   # 8:48 AM
    - cron: '14 9 * * *'   # 9:14 AM
    - cron: '35 9 * * *'   # 9:35 AM
    - cron: '53 10 * * *'  # 10:53 AM
    - cron: '19 11 * * *'  # 11:19 AM
    - cron: '38 11 * * *'  # 11:38 AM
    - cron: '6 12 * * *'   # 12:06 PM
    - cron: '25 12 * * *'  # 12:25 PM
    - cron: '44 13 * * *'  # 1:44 PM
    - cron: '12 14 * * *'  # 2:12 PM
    - cron: '31 14 * * *'  # 2:31 PM
    - cron: '49 15 * * *'  # 3:49 PM
    - cron: '17 16 * * *'  # 4:17 PM
    - cron: '36 16 * * *'  # 4:36 PM
    - cron: '8 17 * * *'   # 5:08 PM
    - cron: '27 17 * * *'  # 5:27 PM
    - cron: '45 18 * * *'  # 6:45 PM
    - cron: '13 19 * * *'  # 7:13 PM
    - cron: '32 19 * * *'  # 7:32 PM
    - cron: '51 20 * * *'  # 8:51 PM
    - cron: '20 21 * * *'  # 9:20 PM
    - cron: '39 21 * * *'  # 9:39 PM
    - cron: '7 22 * * *'   # 10:07 PM
    - cron: '26 22 * * *'  # 10:26 PM
    - cron: '44 23 * * *'  # 11:44 PM
    
    # Additional high-frequency runs for target achievement
    - cron: '58 0 * * *'   # 12:58 AM
    - cron: '16 1 * * *'   # 1:16 AM
    - cron: '34 1 * * *'   # 1:34 AM
    - cron: '54 2 * * *'   # 2:54 AM
    - cron: '22 3 * * *'   # 3:22 AM
    - cron: '42 3 * * *'   # 3:42 AM
    - cron: '3 4 * * *'    # 4:03 AM
    - cron: '24 4 * * *'   # 4:24 AM
    - cron: '45 4 * * *'   # 4:45 AM
    - cron: '7 5 * * *'    # 5:07 AM
    - cron: '26 5 * * *'   # 5:26 AM
    - cron: '47 5 * * *'   # 5:47 AM
    - cron: '9 6 * * *'    # 6:09 AM
    - cron: '31 6 * * *'   # 6:31 AM
    - cron: '50 6 * * *'   # 6:50 AM
    - cron: '13 7 * * *'   # 7:13 AM
    - cron: '34 7 * * *'   # 7:34 AM
    - cron: '55 7 * * *'   # 7:55 AM
    
    # Weekend boost for consistency
    - cron: '2 3 * * 0'    # Sunday 3:02 AM
    - cron: '16 8 * * 0'   # Sunday 8:16 AM
    - cron: '34 13 * * 0'  # Sunday 1:34 PM
    - cron: '47 18 * * 0'  # Sunday 6:47 PM
    - cron: '55 21 * * 0'  # Sunday 9:55 PM
    
    - cron: '21 4 * * 6'   # Saturday 4:21 AM
    - cron: '43 10 * * 6'  # Saturday 10:43 AM
    - cron: '5 15 * * 6'   # Saturday 3:05 PM
    - cron: '22 20 * * 6'  # Saturday 8:22 PM
    - cron: '58 22 * * 6'  # Saturday 10:58 PM
    
  workflow_dispatch:
    inputs:
      contribution_type:
        description: 'Type of contribution to generate'
        required: false
        default: 'random'
        type: choice
        options:
          - random
          - code_optimization
          - documentation_improvement
          - code_comments
          - refactoring_suggestions
          - performance_analysis
          - security_review
          - type_hints_addition
          - error_handling_improvement
          - logging_enhancement
          - configuration_update
          - project_analysis
      force_run:
        description: 'Force run even if recent commits exist'
        required: false
        default: false
        type: boolean

# Add proper permissions for GitHub Actions
permissions:
  contents: write
  actions: write

jobs:
  smart-contribution:
    runs-on: ubuntu-latest
    
    # Prevent multiple instances running simultaneously
    concurrency:
      group: smart-contribution-bot
      cancel-in-progress: false
    
    # Add timeout to prevent runaway processes
    timeout-minutes: 15
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        # Use github.token like the working auto-commit workflow
        token: ${{ github.token }}
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Configure Git
      run: |
        # Use same pattern as auto-commit workflow
        REPO_OWNER="${{ github.repository_owner }}"
        git config --global user.name "$REPO_OWNER"
        git config --global user.email "$REPO_OWNER@users.noreply.github.com"
        echo "Git configured for contributions: $REPO_OWNER"
    
    - name: Check repository permissions
      run: |
        echo "Repository: ${{ github.repository }}"
        echo "Actor: ${{ github.actor }}"
        echo "Token permissions check..."
        git remote -v
        git status
    
    - name: Check for recent commits (smart throttling)
      id: check_commits
      run: |
        # More aggressive throttling - check last 15 minutes only
        RECENT_COMMITS=$(git log --since="15 minutes ago" --oneline | wc -l)
        FORCE_RUN="${{ github.event.inputs.force_run }}"
        
        if [ "$FORCE_RUN" = "true" ]; then
          echo "Force run enabled, proceeding"
          echo "skip=false" >> $GITHUB_OUTPUT
        elif [ $RECENT_COMMITS -gt 1 ]; then
          echo "Recent commits in last 15 minutes ($RECENT_COMMITS), skipping to avoid spam"
          echo "skip=true" >> $GITHUB_OUTPUT
        else
          # Reduced random skip chance for higher frequency (10% instead of 15%)
          RANDOM_SKIP=$((RANDOM % 100))
          if [ $RANDOM_SKIP -lt 10 ]; then
            echo "Random skip for natural variation (10% chance)"
            echo "skip=true" >> $GITHUB_OUTPUT
          else
            echo "Proceeding with contribution"
            echo "skip=false" >> $GITHUB_OUTPUT
          fi
        fi
    
    - name: Run Smart Contribution Bot
      if: steps.check_commits.outputs.skip == 'false'
      env:
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        CONTRIBUTION_TYPE: ${{ github.event.inputs.contribution_type || 'random' }}
      run: |
        # Shorter randomization for higher frequency (optimized for 50/day)
        DELAY=$((RANDOM % 120 + 15))  # 15 seconds to 2 minutes delay
        echo "⏳ Waiting $DELAY seconds for natural timing..."
        sleep $DELAY
        
        # Additional contribution type randomization based on time
        HOUR=$(date +%H)
        if [ "$CONTRIBUTION_TYPE" = "random" ]; then
          # Time-based biases for more natural patterns
          if [ $HOUR -ge 0 ] && [ $HOUR -lt 6 ]; then
            # Night hours: focus on maintenance tasks
            export NIGHT_BIAS="security_review,error_handling_improvement,logging_enhancement"
          elif [ $HOUR -ge 6 ] && [ $HOUR -lt 12 ]; then
            # Morning: documentation and optimization
            export MORNING_BIAS="documentation_improvement,code_optimization,type_hints_addition"
          elif [ $HOUR -ge 12 ] && [ $HOUR -lt 18 ]; then
            # Afternoon: development tasks
            export AFTERNOON_BIAS="refactoring_suggestions,performance_analysis,code_comments"
          else
            # Evening: project analysis and configuration
            export EVENING_BIAS="project_analysis,configuration_update,code_optimization"
          fi
        fi
        
        # Run the smart contribution bot
        python .github/scripts/smart_contribution_bot.py
    
    - name: Push changes with retry
      if: steps.check_commits.outputs.skip == 'false'
      run: |
        echo "[INFO] Checking for changes to commit and push..."
        if [[ -n "$(git status --porcelain)" ]]; then
          echo "Changes detected, pushing..."
          git push origin ${{ github.ref_name }}
          echo "✅ Successfully pushed changes to remote"
        else
          echo "ℹ️ No changes to push"
        fi
    
    - name: Verify changes
      if: steps.check_commits.outputs.skip == 'false'
      run: |
        if [ -d "ai_improvements" ]; then
          echo "✅ AI improvements directory created"
          IMPROVEMENT_COUNT=$(find ai_improvements -name "*.md" | wc -l)
          echo "📄 Total improvement files: $IMPROVEMENT_COUNT"
          echo "📄 Latest files:"
          ls -lt ai_improvements/*.md | head -3
        fi
        
        if [ -f "smart_bot_activity.json" ]; then
          echo "✅ Smart bot activity log updated"
          echo "📊 Current stats:"
          cat smart_bot_activity.json | jq '.total_contributions, .contribution_types'
        fi
    
    - name: Log daily progress
      if: steps.check_commits.outputs.skip == 'false'
      run: |
        if [ -f "smart_bot_activity.json" ]; then
          TOTAL=$(cat smart_bot_activity.json | jq '.total_contributions')
          TODAY_COUNT=$(git log --since="24 hours ago" --oneline --grep="AI Enhancement" | wc -l)
          
          echo "🎯 Daily Progress Tracker:"
          echo "   📈 Total Contributions: $TOTAL"
          echo "   📅 Today's Contributions: $TODAY_COUNT"
          echo "   🎲 Target: 50 per day"
          
          if [ $TODAY_COUNT -ge 45 ]; then
            echo "🏆 Excellent progress! Near daily target!"
          elif [ $TODAY_COUNT -ge 30 ]; then
            echo "✅ Good progress towards daily target"
          elif [ $TODAY_COUNT -ge 15 ]; then
            echo "📊 Moderate progress, ramping up"
          else
            echo "🚀 Starting daily contribution cycle"
          fi
        fi 